### ISSUE TITLE
:sparkles: **GUI Water Tracker for Linux** :sparkles:

### ISSUE THREAD

**Issue by dru18** [dru18/trackwater#16]
- [x] Create functional Application.
- [x] Create necessary Library.
- [x] Create logs.
- [x] Create Install.sh
- [x] Create Uninstall.sh
- [x] Create README.md file.
- [ ] Create Icon.
- [ ] Create style-sheet.
