### ISSUE TITLE
:sparkles: **CLI Water Tracker for Linux** :sparkles:

### ISSUE THREAD

**Issue by dru18** [dru18/trackwater#17]
- [ ] Create functional Application.
- [ ] Create necessary Library.
- [ ] Create Install.sh
- [ ] Create Uninstall.sh
- [ ] Create README.md file.
